include $(APPDIR)/Make.defs

PROGNAME = sim_lvgl
PRIORITY = $(CONFIG_MCP_APPS_SIM_LVGL_PRIORITY)
STACKSIZE = $(CONFIG_MCP_APPS_SIM_LVGL_STACKSIZE)
MODULE = $(CONFIG_MCP_APPS_SIM_LVGL)

# sim_lvgl Example

MAINSRC = sim_lvgl.c

include $(APPDIR)/Application.mk
